### ISSUE TITLE
Player permissions not working

### ISSUE THREAD

**Issue by tylerking** [Dasfaust/GlobalMarket#88] opened 2016-04-01 06:33 UTC
Currently the commands can only be used if you are OP. I use zPermissions and gave my default players the globalmarket.use permission node but they were still unable to list market items.

**Comment by Pigna** [comment] 2016-04-01 07:56
How do your players use the market? what command?

In the version 2.0 (Beta)
The players are suppose to add items without a command.
/market -> Listings -> Drop item on a class pane -> Right click it -> Use [1-9] keys while hovering over left item to increase price, hover over right and [1-9] to increase ammount to sell for that price.

then click the green pane to confirm the enlisting. U can drop to a maximum om 320 items on the enlisting. It will sell for that price untill there are nomore items left in the enlisting.

Still questions? Ill be glad to awnser them.

**Comment by DraksterAU** [comment] 2016-04-01 15:20
In 2.0 You can list items using /market create. 
There are serious bugs with 2.0 though (i.e You cant create server listings at all...) I'd recommend jumping back to 1.3.x.

**Comment by Time6628** [comment] 2016-04-01 17:22
@DraksterAU I can create server listings just fine with GM2. Make sure you installed it right.

**Comment by DraksterAU** [comment] 2016-04-01 17:24
@Time6628 Build 26+? 
How are you making them?

**Comment by Time6628** [comment] 2016-04-01 17:24
./market createinf <price> <amount>

**Comment by doitliketyler** [comment] 2016-04-01 17:30
I used the /market command as well and it's definitely broken and it's not because I didn't install the plugin right. I'm running on Spigot 1.9.2 and there is no errors in console. It does tell me that I need to be holding an item in my hand but I am holding an item do that's wrong too.

**Comment by Time6628** [comment] 2016-04-01 17:49
@doitliketyler Did you install the ProtocolLib? If you did, did you install the right version?

**Comment by DraksterAU** [comment] 2016-04-01 17:53
Yes.

https://github.com/Dasfaust/GlobalMarket/issues/84 occurs for me too.

**Comment by doitliketyler** [comment] 2016-04-01 17:54
Yes.

**Comment by Time6628** [comment] 2016-04-01 17:54
Don't know then. Everything works fine for me.

**Comment by NoHoPeLess** [comment] 2016-04-09 10:51
Yes permissions and the createserverlisting command dont work anymore... anyone can help or is this for the moment broken?

**Comment by DraksterAU** [comment] 2016-04-09 10:54
I've just stayed ok 1.3.... Haha 

Will wait for this to be fixed - along with the others

**Comment by Dasfaust** [comment] 2016-04-18 11:31
Sorry, busy month. I use also zPermissions and don't seem to have this issue. I've added debug output to commands if you want to try that. Enable debug output in your config, restart, and you should see something like "Permissions check on *player* for *permission* has returned true/false".

**Comment by DraksterAU** [comment] 2016-04-18 12:05
@Dasfaust There are several other game breaking bugs (like inability to create a server listing) with your latest 2.0 builds man :) Just making sure your aware haha (all are on GitHub)

**Comment by NoHoPeLess** [comment] 2016-04-18 13:26
any chance when u have time u update this?

**Comment by NoHoPeLess** [comment] 2016-04-18 13:29
also i mean all the bugs? glitching dupe etc ?

**Comment by Dasfaust** [comment] 2016-04-18 13:32
The latest build has an untested fix for createserverlisting. There's no dupe bugs to my knowledge, the [last one reported](https://github.com/Dasfaust/GlobalMarket/issues/77) was fixed.

**Comment by NoHoPeLess** [comment] 2016-04-18 13:35
When im at home, i make an video :D

**Comment by NoHoPeLess** [comment] 2016-04-18 20:23
Here you can see the bug: https://youtu.be/HyRkMxfL5RY

**Comment by Dasfaust** [comment] 2016-04-19 00:34
That's just CraftBukkit/Spigot being wonky. There's improvements to be done but I don't see any duplication happening there so it's low priority.

**Comment by DraksterAU** [comment] 2016-04-19 01:23
@Dasfaust so your opinion is 2.0 is ready for production then? Minus the minor graphical glitches?

**Comment by Time6628** [comment] 2016-04-19 01:35
@Dasfaust Don't mean to burst your bubble, but the commit to fix createserverlisting breaks all market subcommands. I believe the problem is that it searches for what the subcommand starts with, "createinf" doesn't work because it starts with "create" so the plugin will try to do the create subcommand. Same for list. The simple fix for this is to add another alias for createserverlisting/createinf/listinf. :cat:

**Comment by NoHoPeLess** [comment] 2016-04-19 10:19
@Dasfaust with this glitch my items are away..low priority?

**Comment by DraksterAU** [comment] 2016-05-01 13:18
+1 to reproducing @NoHoPeLess issue in v1.7.10 with Thermos (Cauldron)

**Comment by Dasfaust** [comment] 2016-05-01 21:24
Happens in 1.9 too. I can only get the item to stay in the slot via spam-clicking it in, so it's weird. I'm thinking about filling all unused slots with gray stained glass panes as a quick fix.

**Comment by DraksterAU** [comment] 2016-05-01 23:02
@Dasfaust Make the panel a diff color glass slot and bingo, that's perfect.

**Closed** 2024-05-26 23:55 UTC
Labels: wontfix
